services:
  mongodb:
    image: mongo:7.0
    container_name: bank-ods-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: bank_ods

volumes:
  mongo_data:
